language: php

sudo: false

dist: trusty

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

env:
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.2.*"
    - SYMFONY_VERSION="3.3.*"
    - SYMFONY_VERSION="3.4.x-dev"
    - SYMFONY_VERSION="dev-master"

matrix:
    exclude:
        - php: 5.5
          env: SYMFONY_VERSION="dev-master"
        - php: 5.6
          env: SYMFONY_VERSION="dev-master"
        - php: 7.0
          env: SYMFONY_VERSION="dev-master"
        - php: hhvm
          env: SYMFONY_VERSION="dev-master"

before_script:
    - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist --no-interaction --no-progress

script:
    - vendor/bin/phpunit

notifications:
    email:
        - antalaron@antalaron.hu

cache:
    directories:
        - $HOME/.composer/cache
